services:
  # Backend API Server - build from local source
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: tune-vote-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      # Use SQLite for simplicity - no MongoDB needed
      DB_TYPE: file
    ports:
      - "5000:5000"
    networks:
      - tune-vote-network
    volumes:
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: tune-vote-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - tune-vote-network

volumes:
  app_data:
    driver: local

networks:
  tune-vote-network:
    driver: bridge